name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build C++
      run: |
        mkdir src/build
        cd src/build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make

    - name: Tests
      run: |
        ./src/build/tests
