name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build C++
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Test
      run: |
        # Add commands for testing your C++ program here

    # Add additional steps for deployment or other tasks as neede
