name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build C++
      run: |
        mkdir src/build
        cd src/build
        cmake ..
        make

    - name: Test
      run: |
        # Add commands for testing your C++ program here
        ls

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    # Add additional steps for deployment or other tasks as neede
